[pytest]
DJANGO_SETTINGS_MODULE = scoutcore.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = app
env =
    DJANGO_DATABASE_ENGINE=django.db.backends.sqlite3
    POSTGRES_DB=test_scout
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=postgres
    POSTGRES_HOST=localhost
    POSTGRES_PORT=5432