# Generated by Django 5.0.4 on 2026-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва навички')),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Посада')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія')),
                ('url', models.URLField(unique=True, verbose_name='Посилання')),
                ('description', models.TextField(verbose_name='Опис вакансії')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='ЗП від')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='ЗП до')),
                ('source', models.CharField(choices=[('DOU', 'DOU.ua'), ('DJINNI', 'Djinni.co')], max_length=20, verbose_name='Джерело')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='vacancies', to='scout.skill', verbose_name='Ключові навички')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-pub_date'],
            },
        ),
    ]
