# Generated by Django 5.0.4 on 2026-05-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_sent_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Відправлено в ТГ'),
        ),
    ]
