# Generated by Django 5.0.4 on 2026-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_vacancy_is_sent_to_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Повна зайнятість'), ('PART', 'Неповна зайнятість'), ('INTERN', 'Стажування/Інтернатура'), ('FREELANCE', 'Фріланс/Проєкт')], max_length=20, null=True, verbose_name='Тип зайнятості'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Віддалено'), ('OFFICE', 'Офіс'), ('HYBRID', 'Гібрид')], max_length=20, null=True, verbose_name='Формат роботи'),
        ),
    ]
